name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and deploy
        run: |

          # Add your Google Analytics tracking code to your HTML files
          echo '<!-- Google Analytics Tracking Code -->' >> ./index.html
          echo '<script async src="https://www.googletagmanager.com/gtag/js?id=G-45Z12S039Z"></script>' >> ./index.html
          echo '<script>' >> ./index.html
          echo '  window.dataLayer = window.dataLayer || [];' >> ./index.html
          echo '  function gtag(){dataLayer.push(arguments);}' >> ./index.html
          echo '  gtag("js", new Date());' >> ./index.html
          echo '  gtag("config", "G-45Z12S039Z");' >> ./index.html
          echo '</script>' >> ./index.html

          # Deploy to GitHub Pages
          git config --global user.name "${{ secrets.GITHUB_ACTOR }}"
          git config --global user.email "${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"
          git remote add gh-pages https://github.com/${{ github.repository }}.git
          git checkout -b gh-pages
          git add -A
          git commit -m "Deploy to GitHub Pages"
          git push --force gh-pages

        env:
          JEKYLL_ENV: production
        # Use your appropriate static site generator environment variable if not Jekyll
